INDIAN_CITY_STATE = {
    "Mumbai": "Maharashtra",
    "Delhi": "Delhi",
    "Bengaluru": "Karnataka",
    "Hyderabad": "Telangana",
    "Ahmedabad": "Gujarat",
    "Chennai": "Tamil Nadu",
    "Kolkata": "West Bengal",
    "Pune": "Maharashtra",
    "Jaipur": "Rajasthan",
    "Surat": "Gujarat",
    "Lucknow": "Uttar Pradesh",
    "Kanpur": "Uttar Pradesh",
    "Nagpur": "Maharashtra",
    "Indore": "Madhya Pradesh",
    "Bhopal": "Madhya Pradesh",
    "Patna": "Bihar",
    "Vadodara": "Gujarat",
    "Ludhiana": "Punjab",
    "Agra": "Uttar Pradesh",
    "Nashik": "Maharashtra",
    "Faridabad": "Haryana",
    "Meerut": "Uttar Pradesh",
    "Rajkot": "Gujarat",
    "Kalyan-Dombivli": "Maharashtra",
    "Vasai-Virar": "Maharashtra",
    "Varanasi": "Uttar Pradesh",
    "Srinagar": "Jammu and Kashmir",
    "Aurangabad": "Maharashtra",
    "Dhanbad": "Jharkhand",
    "Amritsar": "Punjab",
    "Navi Mumbai": "Maharashtra",
    "Allahabad": "Uttar Pradesh",
    "Ranchi": "Jharkhand",
    "Howrah": "West Bengal",
    "Coimbatore": "Tamil Nadu",
    "Jabalpur": "Madhya Pradesh",
    "Gwalior": "Madhya Pradesh",
    "Vijayawada": "Andhra Pradesh",
    "Jodhpur": "Rajasthan",
    "Madurai": "Tamil Nadu",
    "Raipur": "Chhattisgarh",
    "Kota": "Rajasthan",
    "Guwahati": "Assam",
    "Chandigarh": "Chandigarh",
    "Solapur": "Maharashtra",
    "Hubli-Dharwad": "Karnataka",
    "Tiruchirappalli": "Tamil Nadu",
    "Bareilly": "Uttar Pradesh",
    "Mysore": "Karnataka",
    "Thiruvananthapuram": "Kerala"
}

USA_CITY_STATE = {
    "New York": "New York",
    "Los Angeles": "California",
    "Chicago": "Illinois",
    "Houston": "Texas",
    "Phoenix": "Arizona",
    "Philadelphia": "Pennsylvania",
    "San Antonio": "Texas",
    "San Diego": "California",
    "Dallas": "Texas",
    "San Jose": "California",
    "Austin": "Texas",
    "Jacksonville": "Florida",
    "Fort Worth": "Texas",
    "Columbus": "Ohio",
    "Charlotte": "North Carolina",
    "San Francisco": "California",
    "Indianapolis": "Indiana",
    "Seattle": "Washington",
    "Denver": "Colorado",
    "Washington": "District of Columbia",
    "Boston": "Massachusetts",
    "El Paso": "Texas",
    "Nashville": "Tennessee",
    "Detroit": "Michigan",
    "Oklahoma City": "Oklahoma",
    "Las Vegas": "Nevada",
    "Portland": "Oregon",
    "Memphis": "Tennessee",
    "Louisville": "Kentucky",
    "Baltimore": "Maryland"
}

